server:
  port: 9095

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/llm

  main:
    web-application-type: reactive
  application:
    name: "LLM-Backend-Service"


  datasource:
    url: jdbc:mysql://localhost:3306/LLM_DB
    username: dev
    password: shehan@123
    driver-class-name: com.mysql.cj.jdbc.Driver

    ai:
      mcp:
        server:
          enabled: true
          transport: web
          path: /mcp

logging:
  level:
    org.springframework.ai.mcp: DEBUG
    org.springframework.web.reactive: DEBUG

intelligent-srv:
  url: http://localhost:8500
