package com.shehan.llmsvr.mcpTools;

import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Service
public class SQLTool {

    private final JdbcClient jdbcClient;

    public SQLTool(JdbcClient jdbcClient) {
        this.jdbcClient = jdbcClient;
    }

    @Tool(name = "sql_tool", description = "Execute any SQL query (SELECT, CREATE, UPDATE, DELETE, DESCRIBE)")
    public List<Map<String, Object>> executeQuery(
            @ToolParam(description = "The full SQL SELECT, CREATE, UPDATE, DELETE, DESCRIBEquery generated by the LLM") String query
    ) {
        return jdbcClient.sql(query)
                .query()
                .listOfRows();
    }
}
